/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddKeyDialog: typeof import('./src/components/Dialog/AddKeyDialog.vue')['default']
    AddLangDialog: typeof import('./src/components/Dialog/AddLangDialog.vue')['default']
    AddObjectDialog: typeof import('./src/components/Dialog/AddObjectDialog.vue')['default']
    CopyKeyDialog: typeof import('./src/components/Dialog/copyKeyDialog.vue')['default']
    CopyObjectDialog: typeof import('./src/components/Dialog/copyObjectDialog.vue')['default']
    Grid: typeof import('./src/components/Grid/Grid.vue')['default']
    GridColumn: typeof import('./src/components/Grid/GridColumn.vue')['default']
    IIcBaselineContentCopy: typeof import('~icons/ic/baseline-content-copy')['default']
    KeyEditor: typeof import('./src/components/keyEditor.vue')['default']
    MoveKeyDialog: typeof import('./src/components/Dialog/moveKeyDialog.vue')['default']
    MoveObjectDialog: typeof import('./src/components/Dialog/moveObjectDialog.vue')['default']
    NewKeyField: typeof import('./src/components/newKeyField.vue')['default']
    NewObjectField: typeof import('./src/components/newObjectField.vue')['default']
    RenameObjectDialog: typeof import('./src/components/Dialog/renameObjectDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./src/components/Dialog/SearchDialog.vue')['default']
    SidebarTree: typeof import('./src/components/SidebarTree.vue')['default']
  }
}
